[package]
name = "LF35902"
version = "0.1.0"
description = "Gameboy emulator written in Rust and WebAssembly"
authors = ["Raphael Amorim <rapha850@gmail.com>"]
edition = "2021"

[lib]
name = "LF35902"
path = "src/lib.rs"
crate-type = ["cdylib"]

[[bin]]
name = "LF35902"
path = "src/bin.rs"
test = false
bench = false

[dependencies]
clap = { version = "3.1.17", features = ["derive"] }

# This is for later, when implementing WASM
# wasm-bindgen = "0.2"
# tokio = { version = "1.0", features = ["full"] }
# axum = "0.5.13"
