[package]
name = "LR35902"
version = "0.1.0"
description = "Gameboy emulator written in Rust and WebAssembly"
authors = ["Raphael Amorim <rapha850@gmail.com>"]
edition = "2021"

[lib]
name = "LR35902"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "LR35902"
path = "src/server.rs"
test = false
bench = false

[dependencies]
wasm-bindgen = "0.2.74"
axum = "0.5.13"
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.3.0", features = ["fs"] }

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]
