[package]
name = "LR35902"
version = "0.1.0"
description = "Gameboy emulator written in Rust and WebAssembly"
authors = ["Raphael Amorim <rapha850@gmail.com>"]
repository = "https://github.com/raphamorim/LR35902"
license = "MPL-2.0"
edition = "2021"

[lib]
name = "LR35902"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "LR35902"
path = "src/bin.rs"
test = false
bench = false

[dependencies]
wasm-bindgen = "0.2.74"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]
