[package]
name = "LR35902"
version = "0.1.0"
description = "Gameboy emulator written in Rust and WebAssembly"
authors = ["Raphael Amorim <rapha850@gmail.com>"]
repository = "https://github.com/raphamorim/LR35902"
license = "MPL-2.0"
edition = "2021"

[lib]
name = "lr35902"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
# js-sys = "0.3.59"
# wasm-bindgen = "0.2.82"
glutin = "0.28.0"
libc = "0.2.126"
gl = "0.14.0"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'CanvasRenderingContext2d',
  'CssStyleDeclaration',
  'Document',
  'Element',
  'EventTarget',
  'HtmlCanvasElement',
  'HtmlElement',
  'MouseEvent',
  'Node',
  'Window',
]
