name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RUST_LOG: debug

    steps:
      - name: Checkout source Git repo
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
          use-tool-cache: true

      - name: Make Lint
        run: make lint

      - name: Make desktop build
        run: make desktop-build