name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: rustup toolchain install stable --profile minimal --target ${{ matrix.target }}
      - run: rustup component add rustfmt clippy
      - run: cargo fetch
      - run: cargo fmt -- --check --color always
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - name: cargo test build
        run: cargo build --tests --release
      - name: cargo test
        run: cargo test --release
      - name: Make desktop build
        run: cd ./examples/desktop && make desktop-build
